org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=mek_simple_engines
mod_name=Mekanism: Simple Engines
mod_file_name=Mekanism Simple Engines
mod_license=Codes: Mofusya's Ornating License, Others: All Rights Reserved
mod_version=1.20.1-release1.0a-forge
mod_group_id=net.mofusya.mek_simple_engines
mod_authors=Omotinomoti
mod_description=A Mekanism addon that adds a new simple generator that can generate FE from nothing!

ornate_version=[1.20.1-release1.2a-forge,)
geckolib_version=4.8.4